CREATE DATABASE eletrodomesticos_saep_db;
USE eletrodomesticos_saep_db;

CREATE TABLE Usuario (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255),
    USU_SENHA VARCHAR(255)
);
CREATE TABLE LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATE
);


CREATE TABLE Produto (
    PRODUTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO_NOME VARCHAR(255),
    PRODUTO_QNTD_ESTOQUE INT,
    PRODUTO_FORNECEDOR VARCHAR(255),
    PRODUTO_CATEGORIA VARCHAR(255),
    PRODUTO_POTENCIA VARCHAR(50),
    PRODUTO_GARANTIA VARCHAR(255),
    PRODUTO_CONSUMO_ENERGETICO VARCHAR(255),
    PRODUTO_PRIORIDADE_REPOSICAO VARCHAR(255),
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES Usuario(USU_ID) ON DELETE CASCADE
);


CREATE TABLE Estoque (
    ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTQ_QUANTIDADE INT,
    ESTQ_EMITE_ALERTA VARCHAR(255),
    ESTQ_FORNECEDOR VARCHAR(255),
    FK_PRODUTO_ID INT,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES Produto(PRODUTO_ID) ON DELETE CASCADE
);


-- USUÁRIOS
INSERT INTO Usuario (USU_NOME, USU_EMAIL, USU_SENHA) VALUES
('Gabriel Silva', 'gabriel@email.com', '123456'),
('Leonardo Costa', 'leonardo@email.com', 'senha456'),
('Luiz Pereira', 'luiz@email.com', 'abc@123');

-- PRODUTOS
INSERT INTO Produto (PRODUTO_NOME, PRODUTO_QNTD_ESTOQUE, PRODUTO_FORNECEDOR, PRODUTO_CATEGORIA, PRODUTO_POTENCIA, PRODUTO_GARANTIA, PRODUTO_CONSUMO_ENERGETICO, PRODUTO_PRIORIDADE_REPOSICAO, FK_USU_ID) VALUES
('Geladeira Frost Free', 20, 'EletroMais', 'Refrigeração', '200W', '24 meses', 'A+', 'Alta', 1),
('Fogão 4 bocas', 15, 'CozinhaMax', 'Cozinha', '1600W', '12 meses', 'B', 'Média', 2),
('Liquidificador Turbo', 30, 'Mixlar', 'Pequenos Eletros', '900W', '18 meses', 'A++', 'Baixa', 3);

-- ESTOQUE
INSERT INTO Estoque (ESTQ_QUANTIDADE, ESTQ_EMITE_ALERTA, ESTQ_FORNECEDOR, FK_PRODUTO_ID) VALUES
(10, 'Sim', 'EletroMais', 1),
(5, 'Sim', 'CozinhaMax', 2),
(25, 'Não', 'Mixlar', 3);

-- LOGS
INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA_HORA) VALUES
('Produto Geladeira cadastrado com sucesso', '2025-11-01'),
('Estoque atualizado para Fogão 4 bocas', '2025-11-02'),
('Nova entrada de Liquidificador registrada', '2025-11-03');
